### ISSUE TITLE
write api documentation 

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/RandomProfileGenerator#20]
write basic API documentation, for endpoints for offline users. nothing fancy is required.
Automatic Interactive Documentation is already available by Fastapi.

API code is available in the API folder.

Interactive Documentation can be found by the running server at.

`/docs`
`/redoc`

**Comment by nish-ahmd-it** [comment]
Can you please assign the task to me

**Comment by DrakeEntity** [comment]
@nish-ahmd-it are you working on the docs part? please confirm the status
