### ISSUE TITLE
Funding yml doesn't work

### ISSUE THREAD

**Issue by FahimFBA** [Py-Contributors/RandomProfileGenerator#41]
**Are you using latest code**
Yes.
**Describe the bug**
The funding yml doesn't work properly in this repo. However, I am adding a pull request to solve that.

**Comment by codePerfectPlus** [comment]
It's disabled in settings. Thanks 

![image](https://user-images.githubusercontent.com/54245038/198887029-b7eacb24-8f7f-4eed-8b5d-ba4143a8d4e7.png)

**Comment by ExpressHermes** [comment]
@codePerfectPlus Should we close the issue?

**Comment by codePerfectPlus** [comment]
Yup

**Comment by FahimFBA** [comment]
Ops! Sorry for that. I didn't notice before adding the PR.

**Comment by codePerfectPlus** [comment]
Not an issue 😊
