### ISSUE TITLE
Planning to extend module support

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/RandomProfileGenerator#43]
Planning to extend module support to other platforms/languages as well

- apt Package Manager 
- ~Node Package Manager~

**Comment by ExpressHermes** [comment]
@codePerfectPlus Can you explain a bit more on what you mean by extend module support to other platforms? I am asking since the module is written in python so when extending support to say NPM, you want to write this module in JavaScript (or typescript).

**Comment by codePerfectPlus** [comment]
yup, I am thinking to write the module in Javascript/Typescript as well so it could be available on NPM as well. I am not sure whether to create monorepo(to add javascript code in this repo) or to create a separate repository for javascript.

**Comment by ExpressHermes** [comment]
Got it. I think we should try to focus on python module before moving on to other platforms since in NPM fakers already provides this functionality. What do you think?

**Comment by codePerfectPlus** [comment]
I haven't checked the npm libraries yet for fake data. Thanks for informing me. 
so we can publish it on the apt package manager, no new code to write for that. 
you are right, we should focus on the python module first. @ExpressHermes
