### ISSUE TITLE
Feature: Proposed feature in upcoming version

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/RandomProfileGenerator#44]
## Proposed Feature in Upcoming version(Draft)

1. Data should be generated based on Gender. `fname` file will be rewritten. There will be 2 files.
- `fname_male.txt`
- `fname_female.txt`

2. Generate Geo Coordinate, should be from the same city.
-  `40° 43' 50.1960'' N and 73° 56' 6.8712'' W.`
3. Generate Father/Mother's name as well in the profile section. 
- `fname_male.txt and `fname_female.txt` will be required for this task
4. Generate fake Credit/Debit Card
- `3774-1517-3429-7001, 07/29` 
5. with the job title there should be job experience it should match with age 😁. 
- output key name - `job_experience`

## Current Output Format
```JSON
{
  "first_name": "Kyler",
  "last_name": "Mcclain",
  "hair_color": "brown",
  "blood_type": "(AB-)",
  "full_name": "Kyler Mcclain",
  "DOB": "10/11/1953",
  "age": 69,
  "height": 199,
  "weight": 106,
  "phone": "+1-405-968-1870",
  "address": "268 Pearl St. South Park IL 19112",
  "email": "kylermcclain@usa.com",
  "job_title": "School Teacher",
  "ip_address": "189.214.121.77"}
```

@ExpressHermes Thanks for the suggestion and your input on the proposed features.

**Comment by DavidCano98** [comment]
Hey, @codePerfectPlus , could you please assign mne to this issue? Would like to work on it in the comming days :)

**Comment by codePerfectPlus** [comment]
@DavidCano98 There are 5 issues, please let me know on which issues you want to contribute. I have added more details about the task. we can discuss more if needed. Please suggest if there is anything that needs to improve in the task.

**Comment by DavidCano98** [comment]
I'd actually like to contribute to all 5 points in this issue. And also yes, I can see the description has been updated, thank you for the details.

**Comment by DavidCano98** [comment]
btw @codePerfectPlus , I sent you (I assume it's you) a friend request on Discord where I'd like to ask about a few things, could you please accept when you are able to?

**Comment by codePerfectPlus** [comment]
@DavidCano98 I didn't get any friend requests. I am sharing my discord ID
`soundsLikecrazy#9794`
